// Column metadata definitions for GenericList component
// Each column metadata object may include the following properties:
//   field: string - key in the data item
//   displayName: string - column header label
//   component: Preact component (optional) - custom cell component, receives props { value, item }
//   render: function (optional) - custom render function, signature (value, item) => html
export const columnsConfig = {
  exchanges: [
    { field: 'vhost', displayName: 'Vhost' },
    { field: 'name', displayName: 'Name' },
    { field: 'message_stats', displayName: 'Message Stats' },
    { field: 'message_stats.publish_in_details.rate', displayName: 'Publish In', render: (value) => `${value != null ? value.toFixed(2) : (0.0).toFixed(2)}/s` },
    { field: 'policy', displayName: 'Policy' },
    { field: 'auto_delete', displayName: 'Auto Delete' },
    { field: 'durable', displayName: 'Durable' },
    { field: 'internal', displayName: 'Internal' },
    { field: 'type', displayName: 'Type' },
    { field: 'arguments', displayName: 'Arguments' },
    { field: 'user_who_performed_action', displayName: 'User Who Performed Action' },
  ],
  queues: [
    { field: 'arguments', displayName: 'Arguments' },
    { field: 'auto_delete', displayName: 'Auto Delete' },
    { field: 'consumer_capacity', displayName: 'Consumer Capacity' },
    { field: 'consumer_utilisation', displayName: 'Consumer Utilisation' },
    { field: 'consumers', displayName: 'Consumers' },
    { field: 'durable', displayName: 'Durable' },
    { field: 'effective_policy_definition', displayName: 'Effective Policy Definition' },
    { field: 'exclusive', displayName: 'Exclusive' },
    { field: 'exclusive_consumer_tag', displayName: 'Exclusive Consumer Tag' },
    { field: 'garbage_collection', displayName: 'Garbage Collection' },
    { field: 'head_message_timestamp', displayName: 'Head Message Timestamp' },
    { field: 'idle_since', displayName: 'Idle Since' },
    { field: 'memory', displayName: 'Memory' },
    { field: 'message_bytes', displayName: 'Message Bytes' },
    { field: 'message_bytes_paged_out', displayName: 'Message Bytes Paged Out' },
    { field: 'message_bytes_persistent', displayName: 'Message Bytes Persistent' },
    { field: 'message_bytes_ram', displayName: 'Message Bytes RAM' },
    { field: 'message_bytes_ready', displayName: 'Message Bytes Ready' },
    { field: 'message_bytes_unacknowledged', displayName: 'Message Bytes Unacknowledged' },
    { field: 'message_stats', displayName: 'Message Stats' },
    { field: 'messages', displayName: 'Messages' },
    { field: 'messages_details', displayName: 'Messages Details' },
    { field: 'messages_paged_out', displayName: 'Messages Paged Out' },
    { field: 'messages_persistent', displayName: 'Messages Persistent' },
    { field: 'messages_ram', displayName: 'Messages RAM' },
    { field: 'messages_ready', displayName: 'Messages Ready' },
    { field: 'messages_ready_details', displayName: 'Messages Ready Details' },
    { field: 'messages_ready_ram', displayName: 'Messages Ready RAM' },
    { field: 'messages_unacknowledged', displayName: 'Messages Unacknowledged' },
    { field: 'messages_unacknowledged_details', displayName: 'Messages Unacknowledged Details' },
    { field: 'messages_unacknowledged_ram', displayName: 'Messages Unacknowledged RAM' },
    { field: 'name', displayName: 'Name' },
    { field: 'node', displayName: 'Node' },
    { field: 'operator_policy', displayName: 'Operator Policy' },
    { field: 'policy', displayName: 'Policy' },
    { field: 'recoverable_slaves', displayName: 'Recoverable Slaves' },
    { field: 'reductions', displayName: 'Reductions' },
    { field: 'reductions_details', displayName: 'Reductions Details' },
    { field: 'single_active_consumer_tag', displayName: 'Single Active Consumer Tag' },
    { field: 'slave_nodes', displayName: 'Slave Nodes' },
    { field: 'state', displayName: 'State' },
    { field: 'synchronised_slave_nodes', displayName: 'Synchronised Slave Nodes' },
    { field: 'type', displayName: 'Type' },
    { field: 'vhost', displayName: 'Vhost' },
  ],
};